config/routes.rb
SampleApp::Application.routes.draw do
 
  resources :users do
    member do
      get :following, :followers, :billable_jobs
    end
  end
 
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]

          resources :jobposts do
            member do
              get :winners
            end
              resources :bids #, :only => [:create, :destroy]
          end

          resources :bids do #, :only => [:create, :destroy] do
              resources :microposts, :only => [:create, :destroy]
          end

  resources :relationships, :only => [:create, :destroy]
  resources :winationships, :only => [:create, :destroy]
  
  root :to => "pages#home"  

  match '/allbids',  :to => 'bids#index'

  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/help',      :to => 'pages#help'
  match '/projects',  :to => 'jobposts#index'
  match '/post_project',  :to => 'jobposts#new'
  match '/preview_project',  :to => 'jobposts#preview'
  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  

end

app/models/jobpost.rb
# == Schema Information
# Schema version: 20110226200446
#
# Table name: jobposts
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  location    :string(255)
#  poster      :string(255)
#  description :text
#  work_type   :integer
#  max_budget  :float
#  timeframe   :datetime
#  skills      :integer
#  expiretime  :datetime   
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  start_date  :datetime
#  overtime    :boolean
#  work_intensity :integer
#  email        :string
#
#  object.strftime("Printed on %m/%d/%Y")   #=> "Printed on 11/19/2007"
#  add an expected start_date
#  need to add boolean for "overtime" boolean
#  need to add work_intensity as expected hours/wk

class Jobpost < ActiveRecord::Base
  
#  default_scope :order => 'jobposts.created_at DESC'
# I removed the default_scope command so that I could implement the 
# Jobpost.order(params[:sort]) command within the _jobfeed_items partial.

  attr_accessible :title, :location, :poster, :description, :work_type, 
                  :max_budget, :duration, :skills, :start_date, :overtime,
                  :work_intensity, :email
  
  belongs_to :user
  has_many :bids,          :dependent => :destroy

  has_many :winationships, :foreign_key => "job_id", :dependent => :destroy
  has_many :workers, :through => :winationships, :source => :user

  validates :start_date, :presence => true
  validates :location, :presence => true, :length => { :maximum => 100 }
  validates :poster, :presence => true, :length => { :maximum => 100 }
  validates :description, :presence => true, :length => { :maximum => 1000 }
  validates :title, :presence => true, :length => { :maximum => 100 }
  
#  validates_numericality_of :work_type, :only_integer => true,
#                                        :message => "Can only be whole number."
#  validates_inclusion_of :work_type, :in => 1..3,
#                                     :message => "Can only be a number between 1 and 3."

  validates :work_type, :presence => true,  :length => { :maximum => 100 }
  

#  validates :skills, :presence => true,     :length => { :maximum => 100 }
  
#  validates_numericality_of :skills, :only_integer => true,
#                                         :message => "Can only be whole number."

  validates_numericality_of :work_intensity, :only_integer => true,
          :message => "must be the number of work hours per week."

#  validates_inclusion_of :skills, :in => 1..3,
#                                      :message => "Can only be a number between 1 and 3."
  # this RSPEC isn't testing properly.  Why?  Only works if I test validates 1-by-1.
  
   # need to validate 
          #  max_budget  :float
         #  timeframe   :datetime
  
  validates :user_id, :presence => true


  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, :presence => true,
                    :format => { :with => email_regex }


  def winner?(worker)
    self.winationships.find_by_worker_id(worker)
    # will return true if Jobpost has user has winner choosen
    # nil will return false; finding anything will be true
  end
  
  def pick_winner!(worker)
    self.winationships.create!(:worker_id => worker.id)
    # will create new row in Relationships table
    # only followed_id has to be set because follower_id is incremented automatically
  end

  def pick_loser!(worker)
    self.winationships.find_by_worker_id(worker).destroy
    # will create new row in Relationships table
    # only followed_id has to be set because follower_id is incremented automatically
  end

end

app/controllers/jobposts_controller.rb
class JobpostsController < ApplicationController
  before_filter :authenticate, :only => [:create, :new, :destroy, :edit, :update]
  before_filter :authorized_user, :only => :destroy
  before_filter :only_poster_user, :only => [:new, :edit, :destroy, :update]
  
  def index
    # page to show all projects (aka BROWSE)
    if signed_in?
           # abv:  performing search through Jobpost model
     	     @title = "Projects"
     	     @jobpost = Jobpost.new
           @search = Jobpost.search(params[:search])
           # stores all of the search results
     	     @jobfeed_items = @search.
             order(sort_column + ' ' + sort_direction).
             paginate(:per_page => 5, :page => params[:page])
    else
    	     @title = "Projects"
     	     @jobpost = Jobpost.new
           @search = Jobpost.search(params[:search])
           # stores all of the search results
     	     @jobfeed_items = @search.
             paginate(:per_page => 5, :page => params[:page])
    end
  end

  def show   # page to show individual projects by ID
    @bid = Bid.new if signed_in?
    @title = "Projects"
    @job = Jobpost.find(params[:id])
    # stores all of the search results
    @jobfeed_items = @job
    @sortbidders = User.joins(:bids).
                  where(:bids => {:jobpost_id => params[:id]}).
                  search(params[:search])
    @bidders = @sortbidders.paginate(:per_page => 30, :page => params[:page])

#   Pre-load the text_area with PLE information.
      @bid.message =
        "<p>I found your project on
        <a href='premiumlegalexchange.com'>Premium Legal Exchange</a>.
        Please contact me about '#{@job.title}.'</p>

        <p>Attached is my resume for your consideration.</p>

        Thank you,<br />
        #{current_user.real_name}<br />"

  end

  def winners # page to show individual projects by ID
    @test = Jobpost.new #this is fake until we get ACH/CC payments done
#   @jobpost is referenced in _ACH_form.html.erb;  it is FAKE!
    @bid = Bid.new if signed_in?
    @title = "Projects"
    @job = Jobpost.find(params[:id])
    @winners = @job.workers.paginate(:per_page => 30, :page => params[:page])
#    @winners_amounts = @winners
    # stores all of the search results
    @jobfeed_items = @job
    @sortbidders = User.joins(:bids).
                  where(:bids => {:jobpost_id => params[:id]}).
                  search(params[:search])
    @bidders = @sortbidders.paginate(:per_page => 30, :page => params[:page])
    @commission = 0.10
    @amount_owed = 0
    
    @winners.each do |winner|
      @amount_owed = @amount_owed +
                     Bid.where({:jobpost_id => params[:id],
                                :user_id => winner.id}).
                     first.amount*@job.work_intensity
    end
    @collectible_amount = @amount_owed*@commission
  end


  def new
    # page to make a new project page (post_project)
    @title = "Post a New Project"
    if signed_in?
          @jobpost = Jobpost.new if signed_in?
          @jobfeed_items = current_user.jobfeed.paginate(:page => params[:page])
          # can probably comment this out @jobfeed_items
    end
  end
  
  def preview
    # page to display a summary of the user's project prior to creating it
	@job = current_user.jobposts.build(params[:jobpost])
	
  end

  def create  #literally creates the post, whereas "new" is for a new post
    @jobpost = current_user.jobposts.build(params[:jobpost])
      if @jobpost.save
        flash[:success] = "Project Created!"
        redirect_to projects_path  # re-directing to projects#index
      else
        @jobfeed_items = []
        render 'jobposts/new'
        # perhaps using render (rather than redirect_to) because this way
        # we can see the errors that are being shown in FLASH msg.
      end
  end

  def edit
    # page to edit project with params ID

  end

  def update
    # updates project with params ID
  end

  def destroy
    @jobpost.destroy
    redirect_back_or root_path
  end

private

  def authorized_user
    @jobpost = Jobpost.find(params[:id])
    redirect_to root_path unless current_user?(@jobpost.user)
  end

  def only_poster_user
    if current_user.account_type == 1 # this is the freelance attorney
        redirect_to root_path, :flash => {:error => "You cannot post a project."}
    end
  end

  def sort_column
    Jobpost.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    # says: if Jobpost model has a column based on params:sort, then use
        # that content to sort the column, otherwise use "title" as default
    # might want to change the default parameter "title" to "expires in"
    # once that feature is implemented
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
    # made "desc" the default so we can see recently posted projects first.
  end

end

app/views/jobposts/_fire.html.erb
<%= form_for @job.winationships.find_by_worker_id(bidder.id),
        :html => { :method => :delete } do |f| %>
	<div class="actions">
        <%= f.hidden_field :worker_id %>
        <%= f.hidden_field :job_id %>
        <%= f.submit "Fire" %>
        </div>
<% end %>

        
<%#= form_for(current_user.relationships.build(:followed_id => @user.id),
     :remote => true) do |f| %>

app/views/jobposts/_hire.html.erb
<%#= form_for(current_user.relationships.build(:followed_id => @user.id),
     :remote => true) do |f| %>

<%= form_for @job.winationships.build(:worker_id => bidder.id) do |f| %>
<!-- remote allows for AJAX  -->
	
          <%= f.hidden_field :worker_id %>
          <%= f.hidden_field :job_id %>
	<!-- the follow/unfollow form doesn’t have any content other than the button,
	but it still needs to send the followed_id, which we accomplish with hidden_field -->
	<div class="actions">
        <%= f.submit "Hire" %>
        </div>
<% end %>

app/views/jobposts/_jobpost.html.erb
<tr>
  <td class="jobpost">

    <span class="title">Title:
    <%= link_to jobpost.title,
                jobpost_path(jobpost.id) %></span>
    <span class="location">Location:  <%= jobpost.location %></span>
    <span class="poster">Posted by:  <%= jobpost.poster %></span>
    <span class="work_type">Type:  <%= jobpost.work_type %></span>
    <span class="max_budget">Max Budget:  $<%= jobpost.max_budget %></span>
    <span class="duration">Duration:  <%= jobpost.duration %></span>
    <span class="skills">Skills:  <%= jobpost.skills %></span>
    <span class="description">Description:  <%= jobpost.description %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(jobpost.created_at) %> ago.
    </span>
    
    	<% if current_user?(@user) %>

	    <%= link_to "Delete Post", jobpost, :method => :delete,
	                                     :confirm => "You sure?",
	                                     :title => jobpost.title %>
        <% end %>
  </td>
</tr>

app/views/jobposts/_pick_winner.html.erb
	<div id="follow_form">
		<% if @job.winner?(@bidders.first) %>
			<%= render 'fire' %>
		<% else %>
			<%= render 'hire' %>
		<% end %>
	</div>

  <%#*def winner?(worker)%>
    <%#*self.winationships.find_by_worker_id(worker)%>

  <%#*def pick_winner!(worker)%>
    <%#*self.winationships.create!(:worker_id => worker.id)%>

  <%#*def pick_loser!(worker)%>

app/views/jobposts/edit.html.erb
<!-- Using a Rails Form Helper -->

<h1>Edit Project</h1>

<%= form_for(@user) do |f| %>

	<%= render 'fields', :f => f %>

	<div class="actions">
		<%= f.submit "Update" %>  
	</div>

<% end %>
<!-- note that the second embedded Ruby does not have = sign ...-->

<div> 
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails" target=_blank>change</a>
</div>

app/views/jobposts/index.html.erb
<!--body container starts-->
<div id="body_container">
    <!--project page box starts-->
  <div id="inner_page">

<h1 class="title_header">Browse Projects</h1>

<% if signed_in? %>
  <% if current_user.account_type != 1 %>
    <%= link_to "Post a New Project", post_project_path, :class => "postproject_button round" %>
  <% end %>
<% end %>

    <div class="search_projects round">
      <%= render 'shared/jobsearch' %>
    </div>

    <div class="browse_projects round">
      <%= render 'shared/jobfeed' %>
    </div>

  </div>
    <!--project page box ends-->
</div>
<!--body container ends-->

app/views/jobposts/index.js.erb
$('#jq_jobfeed').html('<%= escape_javascript(render('shared/jobfeed_item')) %>');

app/views/jobposts/preview.html.erb
<h3>Preview Your Project</h3>
    
<span class="title"><strong>Title: </strong>
                                  <%= @job.title %></span>
<%= render 'shared/jobpost_details' %>

<%= form_for @job do |f| %>
	<%= f.hidden_field :title %>
	<%= f.hidden_field :location %>
	<%= f.hidden_field :email %>
	<%= f.hidden_field :poster %>
	<%= f.hidden_field :work_type %>
	<%= f.hidden_field :max_budget %>
	<%= f.hidden_field :overtime %>
	<%= f.hidden_field :start_date %>
	<%= f.hidden_field :duration %>
	<%= f.hidden_field :work_intensity %>
	<%= f.hidden_field :skills %>
	<%= f.hidden_field :description %>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/jobposts/show.html.erb
<h3>Project: <%= @job.title %></h3>
    
<%= render 'shared/jobpost_details' %>

<% if signed_in? %>
  <div class="place_bid">
          <h3 class="micropost">Apply For This Project</h3>
          <%#= render 'shared/bidpost_form' %>
          <%= render 'shared/apply_for_job_form' %>
  </div>

    <% if @job.user_id == current_user.id %>

      <center><h3><a href="<%= winners_jobpost_path(params[:id]) %>">
          Finished Building My Team </a></h3>
      </center>

<h3>Current Bids</h3>    

      <%= sort_link @sortbidders, :name %> |
      <%= sort_link @sortbidders, :bids_amount %> |
      <%= sort_link @sortbidders, :location %> |
      <%= sort_link @sortbidders, :rating %> |
      <%= sort_link @sortbidders, :jobs_completed %></br>

    <% if @bidders.any? %>
      <div class="bidfeed">
      <%= render :partial => 'shared/bidder', :collection => @bidders %><br/>
      <%#= render :partial => 'shared/bidfeed_item', :collection => @bidfeed_items %>
      </div>
    <% else %>
          <div class="bidfeed">
          <span class="no_results">
            <p>We're sorry but there are no results.</p>
          </span>
        </div>
    <% end %>

      <div class="user_searchbox round">
        <%= render 'shared/bidsearch' %>
      </div>
      <%= will_paginate @bidders %>


                  <% if current_user?(@job.user) %>
         <br/>
                      <%= link_to "Delete Post", @job, :method => :delete,
                                                       :confirm => "You sure?",
                                                       :title => @job.title %>
                  <% end %>
    <% end %>

<% else %>

    <center><h3>
        Please <%= link_to "sign-up", signup_path %> or
               <%= link_to "sign-in", signin_path %> to bid on this project.
    </h3></center> <br/>
<% end %>

app/views/jobposts/winners.html.erb
<center><h3>Complete Your Transaction for</h3></center>
<center><h3><%= @job.title %></h3></center>
                                
    
<table class="jobposts" summary="User jobposts">
  <tr>
        <td class="jobpost">          
          <span class="location"><strong>Location: </strong>
                                  <%= @job.location %></span>

          <span class="poster"><strong>Posted by: </strong>
                             <%= link_to @job.user.name,
                                           @job.user %>
          </span>

          <span class="work_type"><strong>Work Type: </strong>
                      <%= @job.work_type %></span>

          <span class="max_budget"><strong>Max Bid: </strong>$
                      <%= @job.max_budget %></span>

          <span class="overtime"><strong>Pays Overtime: </strong>
                      <%= @job.overtime ? "Yes" : "No" %>
          </span>
        </td>
        <td class="jobpost">
          <span class="start_date"><strong>Start Date:  </strong>
                      <%= @job.start_date ?
                      @job.start_date.strftime("%a, %b. %d, %Y") : "" %>
          </span>

          <span class="duration"><strong>Project Duration: </strong>
                      <%= @job.duration %> weeks
          </span>

          <span class="work_intensity"><strong>Intensity: </strong>
                      <%= @job.work_intensity %> hours per week
          </span>

          <span class="skills"><strong>Skills Sought: </strong>
                      <%= @job.skills %></span>

          <span class="timestamp">Posted
                <%= time_ago_in_words(@job.created_at) %> ago.
          </span>
        </td>
      </tr>
</table>

<table class="jobposts" summary="User jobposts">
  <tr>
        <td class="jobpost">
          <span class="description">
            <strong>Description: </strong><%= @job.description %>
          </span>
        </td>
  </table>

<% if signed_in? %>

    <% if @job.user_id == current_user.id %>
      <h3>You chose the following attorneys:</h3>

    <% if @winners.any? %>
      <div class="escrow">
        <%= render :partial => 'shared/finish_transaction', :collection => @winners %><br/>
      </div>
      <p></p>
      <p>Please escrow <b><%= number_to_currency(@amount_owed) %></b>
      based on the expected number of hours you have alloted for your project.
      The money will be released to the contract attorneys pending your
      approval of their time sheets. </p>
      <p>Based on our commission of
      <b><%= number_to_percentage(@commission*100, :precision => 2) %></b>,
      we will take
      <b><%= number_to_currency(@collectible_amount) %> </b>
      from the escrowed amount.</p>

      <%= render 'shared/ach_form' %>
      
    <% else %>
          <div class="bidfeed">
          <span class="no_results">
            <p>We're sorry but you have not selected any winners.</p>
          </span>
        </div>
    <% end %>
  <% end %>
<% end %>