config/routes.rb
SampleApp::Application.routes.draw do
 
  resources :users do
    member do
      get :following, :followers, :billable_jobs
    end
  end
 
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]

          resources :jobposts do
            member do
              get :winners
            end
              resources :bids #, :only => [:create, :destroy]
          end

          resources :bids do #, :only => [:create, :destroy] do
              resources :microposts, :only => [:create, :destroy]
          end

  resources :relationships, :only => [:create, :destroy]
  resources :winationships, :only => [:create, :destroy]
  
  root :to => "pages#home"  

  match '/allbids',  :to => 'bids#index'

  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/help',      :to => 'pages#help'
  match '/projects',  :to => 'jobposts#index'
  match '/post_project',  :to => 'jobposts#new'
  match '/preview_project',  :to => 'jobposts#preview'
  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  

end

app/models/user.rb
# == Schema Information
# Schema version: 20110221145226
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean
#    add_column :users, :real_name, :string
#    add_column :users, :status, :integer
#    add_column :users, :skills, :text
#    add_column :users, :location, :string
#    add_column :users, :rating, :integer
#    add_column :users, :jobs_completed, :integer
#    add_column :users, :tagline, :text
#    add_column :users, :skill1, :string
#    add_column :users, :skill2, :string
#    add_column :users, :skill3, :string
#    add_column :users, :resume, :text
#    add_column :users, :account_type, :integer

class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation,
                  :real_name, :status, :skills, :location, :tagline, 
                  :skill1, :skill2, :skill3, :resume, :account_type,
                  :rating, :jobs_completed
  #allows users to enter/change their name & email, pswd

  has_many :bids,          :dependent => :destroy
  accepts_nested_attributes_for :bids

  has_many :jobposts,      :dependent => :destroy
  has_many :microposts,    :dependent => :destroy
  has_many :relationships, :dependent => :destroy,
                           :foreign_key => "follower_id"
                          # hardwires the key (id) from one table to another 
  has_many :reverse_relationships, :dependent => :destroy,
                           :foreign_key => "followed_id",
                           :class_name => "Relationship"
                           # class_name tells Rails to fake the reverse_relationships model

  has_many :reverse_winationships, :dependent => :destroy,
                           :foreign_key => "worker_id",
                           :class_name => "Winationship"
                           # class_name tells Rails to fake the reverse_relationships model
  has_many :billable_jobs, :through => :reverse_winationships, :source => :jobpost


  has_many :following, :through => :relationships, 
                       :source => :followed
  has_many :followers, :through => :reverse_relationships, 
                       :source => :follower
                       # :source tells Rails which key column to look at                  

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
                    :length   => { :maximum => 50 } 
  validates :email, :presence => true, 
                    :format => { :with => email_regex },     
                    :uniqueness => { :case_sensitive => false }
  # must follow format validation
  # must follow unique validation
  
  validates :password,  :presence => true, 
                        :confirmation => true,
                        :length   => { :within => 6..40 } 

  validates :account_type,  :presence => true


  # we want to create the encrypted password before the user gets saved to the DB 
  before_save :encrypt_password
  
  def feed
    Micropost.from_users_followed_by(self)    
  end
  
  def jobfeed
    Jobpost.where("user_id = ?", id)    
  end
  
  def following?(followed)
    self.relationships.find_by_followed_id(followed)
    # will return true if user if following another user
    # nil will return false; finding anything will be true
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
    # will create new row in Relationships table
    # only followed_id has to be set because follower_id is incremented automatically
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy    
  end
  
  
  def has_password?(submitted_password)
    # compare submtted password with the encrypted password.
    # this is for the sign-in; user enters a pw; must compare 
    # it to the stored encrypted_password for that user. This method 
    # returns "true" if the passwords match.
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)  #can also be User.authenticate; we're using self because it's a valid class "self" reference
     user = User.find_by_email(email)
     # inside a self class method you can omit the "User." prefix.  It's implicit.
     return nil  if  user.nil?
     return user if user.has_password?(submitted_password) #returns true if submitted pw == encrypted pw
  end  
     # This method handles two cases (1. invalid email and 2. a successful match) with explicit 
     # return keywords, and handles the third case (password mismatch) implicitly, 
     # since in that case we reach the end of the method, which automatically returns nil.   
  # ------------------------------------------------------------------------
  # ------------------------------------------------------------------------
  # BELOW -- additions for authenticating sign-in users from Lesson #9

  def self.authenticate_with_salt(id, cookie_salt)
     user = find_by_id(id)
     (user && user.salt == cookie_salt) ? user : nil
     # IF (boolean AND boolean)? return value for TRUE : return value for FALSE
  end 
  
      
  private
    def encrypt_password
        self.salt = make_salt if new_record?  # make a salt only if it's a new record
        self.encrypted_password = encrypt(self.password)
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
        
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :except => [:show, :new, :create]
  # used to effectuate a redirect to signin if trying to access unauth pages
  # but need an options hash to limit only some pages
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
#    @users = User.all
#  we introduced the paginate method using the 'will_paginate' gem.
#  now instead of User.all, which is an array, we will use the following:

#    @users = User.paginate(:page => params[:page])
    @title = "All Users"
    @user_search = User.search(params[:search])
    @users = @user_search.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
    @microposts = @user.microposts.paginate(:page => params[:page])
    @jobposts = @user.jobposts.paginate(:page => 1)
    
  end
  
  def following 
    @title = "Following" 
    @user = User.find(params[:id])
    @users = @user.following.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers" 
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  def new
    @user = User.new
    @title = "Sign Up"
  end

  def create
    #raise params[:user].inspect
    
    @user = User.new(params[:user])
    if @user.save
      # handle a successful save.
      UserMailer.registration_confirmation(@user).deliver
      # send an email saying registration successful
      sign_in @user
      
      redirect_to user_path(@user), :flash => { :success => "Welcome to PLE!" }
      
    else
      @title = "Sign Up"
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @title = "Edit User"
  end
  
  def update
#    @user = User.find(params[:id])
#    got rid of these because the before_filter is running before :edit and :update;
#    thus don't need this assignment.
    if @user.update_attributes(params[:user])
      redirect_to @user, :flash => { :success => "Profile updated." }
    else
     @title = "Edit User"
     render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    redirect_to users_path, :flash => {:success => "User destroyed."}
  end
  
#---------------------------------
  private
    # def authenticate
    #   deny_access unless signed_in?
    #   # deny_access is located in the sessions_helper for refactoring purposes
    # end
    
    # After Chapter 11 we moved this authenticate method to the Sessions helper so it could be used
    # by the microposts_controller.rb
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
      # unless @user == current_user is very common.  we'll define as method current_user?(@user)
    end
    
    def admin_user
      @user = User.find(params[:id])
      redirect_to(root_path) if (!current_user.admin? || current_user?(@user))
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50})
    gravatar_image_tag(user.email.downcase, :alt => user.name, 
                                            :class => 'gravatar', 
                                            :gravatar => options)
  end
end

app/views/users/_agency_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
        <b>Account Type:</b> Placement Agency <br />
</div>

<div class="field">
	<%= f.label :name %>  <br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :email %>  <br />
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :password %>  <br />  
	<%= f.password_field :password %>  
	<!-- cannot use f.text_field because it shows password when typing -->
</div>	

<div class="field">
	<%= f.label :password_confirmation, "Confirm Password" %>  <br />
	<%= f.password_field :password_confirmation %>
</div>

<div class="field">
	<%= f.label :real_name, "Agency Name" %>  <br />
	<%= f.text_field :real_name %>
</div>

<div class="field">
	<%= f.label :location, "Please enter your ZIP code" %>  <br />
	<%= f.text_field :location %>
</div>

<div class="field">
	<%= f.label :tagline, "Enter a short tagline" %>  <br />
	<%= f.text_area :tagline %>
</div>

<div class="field">
	<%= f.label :resume, "Insert Bio" %>  <br />
	<%= f.text_area :resume %>
</div>

app/views/users/_agency_profile.html.erb
<div class="field">
  <span class="account">
    <b>Account Type:</b> Placement Agency <br />
  </span>

<span class="username">
	<b>Username:</b> <%= @user.name %>  <br />
</span>

<span class="name">
	<b>Agency Name:</b> <%= @user.real_name %>  <br />
</span>

<span class="location">
	<b>Location:</b> <%= @user.location %>  <br />
</span>

<span class="tagline">
	<b>Tagline:</b> <%= @user.tagline %>  <br />
</span>

<span class="resume">
	<b>Bio:</b> <%= @user.resume %>  <br />
</span>

app/views/users/_attorney_profile.html.erb
<div class="field">
  <span class="account">
    <b>Account Type:</b> Freelance Attorney <br />
  </span>

<span class="username">
	<b>Username:</b> <%= @user.name %>  <br />
</span>

<span class="name">
	<b>Agency Name:</b> <%= @user.real_name %>  <br />
</span>

<span class="location">
	<b>Location:</b> <%= @user.location %>  <br />
</span>

<span class="tagline">
	<b>Tagline:</b> <%= @user.tagline %>  <br />
</span>

<span class="resume">
	<b>Bio:</b> <%= @user.resume %>  <br />
</span>

app/views/users/_client_profile.html.erb
<div class="field">
        <b>Account Type:</b> Client <br />
</div>

<div class="field">
	<b>Username:</b> <%= @user.name %>  <br />
</div>

<div class="field">
	<b>Email:</b> <%= @user.email %>  <br />
</div>

<div class="field">
	<b>Company Name:</b> <%= @user.real_name %>  <br />
</div>

<div class="field">
	<b>Location:</b> <%= @user.location %>  <br />
</div>

<div class="field">
	<b>Tagline:</b> <%= @user.tagline %>  <br />
</div>

<div class="field">
	<b>Bio:</b> <%= @user.resume %>  <br />
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
	<%= f.label :name %>  <br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :email %>  <br />
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :password %>  <br />  
	<%= f.password_field :password %>  
	<!-- cannot use f.text_field because it shows password when typing -->
</div>	

<div class="field">
	<%= f.label :password_confirmation, "Confirm Password" %>  <br />
	<%= f.password_field :password_confirmation %>
</div>

<div class="field">
	<%= f.label :real_name, "First and Last Name" %>  <br />
	<%= f.text_field :real_name %>
</div>

    <%=  f.check_box :status %> Are You Available? <br/>

<div class="field">
	<%= f.label :skills, "Please enter your skills here
                              (separated by semicolon)" %>  <br />
	<%= f.text_area :skills %>
</div>

<div class="field">
	<%= f.label :location, "Please enter your ZIP code" %>  <br />
	<%= f.text_field :location %>
</div>

<div class="field">
	<%= f.label :tagline, "Enter a short tagline" %>  <br />
	<%= f.text_area :tagline %>
</div>

<div class="field">
	<%= f.label :skill1, "What are your top three skills?" %>  <br />
	<%= f.text_field :skill1 %> <br />
        <%= f.text_field :skill2 %> <br />
        <%= f.text_field :skill3 %> <br />
</div>

<div class="field">
	<%= f.label :resume, "Enter your resume" %>  <br />
	<%= f.text_area :resume %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(:followed_id => @user.id), 
											  :remote => true) do |f| %>
											<!-- remote allows for AJAX  -->
	 
	<div><%= f.hidden_field :followed_id %>
	<!-- the follow/unfollow form doesn’t have any content other than the button, 
	but it still needs to send the followed_id, which we accomplish with hidden_field -->

	<div class="actions"><%= f.submit "Follow" %></div>

<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'unfollow' %>
		<% else %>
			<%= render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_lawfirm_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
        <b>Account Type:</b> Law Firm <br />
</div>

<div class="field">
	<%= f.label :name %>  <br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :email %>  <br />
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :password %>  <br />  
	<%= f.password_field :password %>  
	<!-- cannot use f.text_field because it shows password when typing -->
</div>	

<div class="field">
	<%= f.label :password_confirmation, "Confirm Password" %>  <br />
	<%= f.password_field :password_confirmation %>
</div>

<div class="field">
	<%= f.label :real_name, "Law Firm Name" %>  <br />
	<%= f.text_field :real_name %>
</div>

<div class="field">
	<%= f.label :skills, "What kind of attorneys are you looking for?" %>
        <br />
	<%= f.text_area :skills %>
</div>

<div class="field">
	<%= f.label :location, "Please enter your ZIP code" %>  <br />
	<%= f.text_field :location %>
</div>

<div class="field">
	<%= f.label :tagline, "Enter a short tagline" %>  <br />
	<%= f.text_area :tagline %>
</div>

<div class="field">
	<%= f.label :resume, "Insert Bio" %>  <br />
	<%= f.text_area :resume %>
</div>

app/views/users/_user.html.erb
<li> 
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? %>
	|
	<%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
	 							:title => "Delete #{user.name}" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<!-- Using a Rails Form Helper -->

<center><h1>Update Your Profile</h1></center>

<%= form_for(@user) do |f| %>

        <% if @user.account_type == 1 %>
          <%= render 'attorney_fields', :f => f %>
        <% elsif @user.account_type == 2 %>
          <%= render 'agency_fields', :f => f %>
        <% elsif @user.account_type == 3 %>
          <%= render 'lawfirm_fields', :f => f %>
        <% else %>
          <%= render 'client_fields', :f => f %>
        <% end %>
  
	<div class="actions">
		<%= f.submit "Update" %>  
	</div>

<% end %>
<!-- note that the second embedded Ruby does not have = sign ...-->

<div> 
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails" target=_blank>change</a>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

  Sort By:
  <%= sort_link @user_search, :name %> |
  <%= sort_link @user_search, :location %> |
  <%= sort_link @user_search, :rating %> |
  <%= sort_link @user_search, :jobs_completed %> | 
  <%= sort_link @user_search, :status %> |</br>

<% if @users.any? %>
    <div class="bidfeed">
      <%= render :partial => 'shared/abbrev_user', :collection => @users %>
    </div>
<% else %>
    <div class="bidfeed">
      <span class="no_results">
        <p>We're sorry but there are no results.</p>
      </span>
    </div>
    <% end %>
<div class="user_searchbox round">
  <%= render 'shared/usersearch' %>
</div>

<%= will_paginate %>

app/views/users/new.html.erb
<!-- Using a Rails Form Helper -->
<!--body container starts-->
<div id="body_container">
    <!--project page box starts-->
  <div id="project_page">

<h1 class="title_header">Sign Up</h1>

<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>

	<%= render 'fields', :f => f %>	

	<div class="actions">
		<%= f.submit "Sign Up" %>  
	</div>

<% end %>
<!-- note that the second embedded Ruby does not have = sign ...-->
  </div>
</div>

app/views/users/show.html.erb
<table class "profile" summary="Profile Information">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
			<%= render 'follow_form' if signed_in? %>
                        <table class "userprofile" summary="user profile">

        <% if @user.account_type == 1 %>
          <%= render 'attorney_profile', :f => @user %>
        <% elsif @user.account_type == 2 %>
          <%= render 'agency_profile', :f => @user %>
        <% elsif @user.account_type == 3 %>
          <%= render 'lawfirm_profile', :f => @user %>
        <% else %>
          <%= render 'client_profile', :f => @user %>
        <% end %>

</table>

      
        <%#*<a href="<%= billable_jobs_user_path(@user) %>">%>
          <%#*<span id="billable_jobs" class="stat">%>
            <%#= @user.billable_jobs.count %>
            <%#*billable jobs%>
          <%#*</span>%>
        <%#*</a>%>
      

        <% if @user.jobposts.any? %>
                <table class="jobposts" summary="User jobposts">
                  <h3>Your Projects</h3>
                  <%= render @jobposts %>

                </table>
                <%= will_paginate @jobposts %>
        <% end %>

        <% if @user.microposts.any? %>
                <table class="microposts" summary="User microposts">
                        <%= render @microposts %>
                        <!-- remember that render requires a _partial.html.erb -->
                </table>
                <%= will_paginate @microposts %>
        <% end %>
			
		</td>	
	</tr>
</table>

app/views/users/show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>

      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
      <% unless @users.empty? %>
        <% @users.each do |user| %>
          <%= link_to gravatar_for(user, :size => 30), user %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>