config/routes.rb
SampleApp::Application.routes.draw do
 
  resources :users do
    member do
      get :following, :followers, :billable_jobs
    end
  end
 
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]

          resources :jobposts do
            member do
              get :winners
            end
              resources :bids #, :only => [:create, :destroy]
          end

          resources :bids do #, :only => [:create, :destroy] do
              resources :microposts, :only => [:create, :destroy]
          end

  resources :relationships, :only => [:create, :destroy]
  resources :winationships, :only => [:create, :destroy]
  
  root :to => "pages#home"  

  match '/allbids',  :to => 'bids#index'

  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/help',      :to => 'pages#help'
  match '/projects',  :to => 'jobposts#index'
  match '/post_project',  :to => 'jobposts#new'
  match '/preview_project',  :to => 'jobposts#preview'
  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  

end

app/views/shared/_abbrev_user.html.erb
<div class="bidtable">
    <span class="name">
      <br><b>User Name </b></br>
        <%= link_to abbrev_user.name, abbrev_user %>
    </span>

    <span class="location">
      <br><b>Location</b></br>
        <%= abbrev_user.location %></span>

    <span class="rating">
      <br><b>Rating</b></br>
      <%#= abbrev_user.rating %>
      <%= (1+rand(10)) %>
    </span>

    <span class="jobs_completed">
      <br><b>No. Jobs</b></br>
      <%#= abbrev_user.jobs_completed %>
      <%= (1+rand(30)) %>
    </span>

      <% if abbrev_user.status == 1 %>
    <span class="yesstatus">
      <strong>Available</strong></span>
      <% else %>
        <span class="nostatus">Unavailable</span>
      <% end %>

    <span class="tagline"><b>Tagline:</b> <%= abbrev_user.tagline %></span>

</div>

app/views/shared/_ach_form.html.erb
<%= form_for @test do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title, "Full Name" %>: <br /><%= f.text_field :title %> <br />
    <%= f.label :location, "Account Number" %>: <br />
                  <%= f.text_field :location %> <br />
    <%= f.label :work_type, "Routing Number" %>: <br />
                  <%= f.text_field :work_type %> <br /></div>
  <div class="actions">
    <%#= f.submit "Submit" %>
    <a href="<%= jobpost_path(params[:id]) %>">
      Submit
    </a>
  </div>
<% end %>

<%# This is a sample form where the payment processing will take place.%>

app/views/shared/_apply_for_job_form.html.erb
<%= form_for(@bid) do |f| %> 
  <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
      <%#= f.label :message %>
      <%= f.tinymce :message %>
      <%#*IMPLEMENT THIS TABLE-LESS MODEL
          http://asciicasts.com/episodes/193-tableless-model%>
      <%= f.hidden_field :jobpost_id, :value => params[:id] %>
    </div>
	
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>

<% end %>

app/views/shared/_bidfeed_item.html - Copy.erb
<tr>  
  <td class="bids">
      <span class="bid_name">
        <%= link_to User.find(bidfeed_item.user_id).name,
                            User.find(bidfeed_item.user_id) %>
      </span>
  </td>
  <td class="bids">
      <span class="bid_amount">
        $<%= bidfeed_item.amount %>
      </span>
  </td>
  <td class="bids">
      <span class="bid_location">
        <%= User.find(bidfeed_item.user_id).location %>
      </span>
  </td>

  <td class="bids">
      <span class="bid_rating">
        <%= User.find(bidfeed_item.user_id).rating ?
            User.find(bidfeed_item.user_id).rating : "--" %>
      </span>
  </td>

  <td class="bids">
      <span class="bid_rating">
        <%= User.find(bidfeed_item.user_id).jobs_completed ?
            User.find(bidfeed_item.user_id).jobs_completed : "--" %>
      </span>
  </td>
  </tr>

app/views/shared/_bidsearch.html.erb
    <% form_for :search, @user_search, :html => {:method => :get} do |f| %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>

<p>        <strong>Bid Amount</strong><br/>
        <%= f.label :bids_amount_gte, "Min" %>
        <%= f.text_field :bids_amount_gte, :size => 3 %>
        <%= f.label :bids_amount_lte, "Max" %>
        <%= f.text_field :bids_amount_lte, :size => 3 %></p>

<p>        <%= f.label :location_contains, "Location" %><br />
        <%= f.text_field :location_contains %>
</p>
<p>        <strong>Rating</strong><br/>
        <%= f.label :rating_gte, "Min" %>
        <%= f.text_field :rating_gte, :size => 3 %>
        <%= f.label :rating_lte, "Max" %>
        <%= f.text_field :rating_lte, :size => 3 %><br />
</p>
<p>        <strong>No. Jobs Completed</strong><br/>
        <%= f.label :jobs_completed_gte, "From" %>
        <%= f.text_field :jobs_completed_gte, :size => 3 %>
        <%= f.label :jobs_completed_lte, "to" %>
        <%= f.text_field :jobs_completed_lte, :size => 3 %><br />
</p>
<p>        <%= f.label :skills_contains, "Skills" %><br />
        <%= f.text_field :skills_contains %><br />
</p>

<p>     <%= f.label :resume_contains, "Resume" %><br />
        <%= f.text_field :resume_contains %><br />
</p>

<p>
        <%= f.label :name_or_location_or_skills_or_tagline_or_resume_contains, "Any Keyword" %><br />
        <%= f.text_field :name_or_location_or_skills_or_tagline_or_resume_contains %><br />
</p>

      <p class="button"><%= f.submit "Search" %></p>
      
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<table class="microposts" summary="Status feed">
		<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
	</table>
	
	<%= will_paginate @feed_items %>

<% end %>

app/views/shared/_feed_item.html.erb
<tr>
	<td class="gravatar">
		<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	</td>
	<td class="micropost">
		<span class="user">
			<%= link_to feed_item.user.name, feed_item.user %>
		</span>
		<span class="content"><%= feed_item.content %></span>
		<span class="timestamp">
			Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
		</span>
	</td>
	<% if current_user?(feed_item.user) %>
		<td>
			<%= link_to "delete", feed_item, :method => :delete, 
											 :confirm => "You sure?", 
											 :title => feed_item.content %>
		</td>
	<% end %>
</tr>		

app/views/shared/_flash_errors.html.erb
<div id="flash_errors">
      <section class="round">
              <% flash.each do |key, value| %>
                      <div class="flash <%= key %>"><%= value %></div>
              <!-- no =% on flash because iterating through Ruby, i.e., "script"-->
              <!-- yes =% on key and value because interpolating variables -->
              <!-- n.b. key within "flash " so we can style different key msg -->
              <% end %>
      </section>
</div>

app/views/shared/_jobfeed_item.html.erb
<tr>
  <td class="jobpost">
  
    <span class="title"><strong>Title: </strong>
      <strong><%= link_to jobfeed_item.title,
                                    jobpost_path(jobfeed_item.id) %></strong>
    </span>

    <span class="location"><strong>Location: </strong>
                            <%= jobfeed_item.location %></span>

    <span class="poster"><strong>Posted by: </strong>
                       <%= link_to jobfeed_item.user.name,
                                     jobfeed_item.user %>
    </span>

    <span class="work_type"><strong>Work Type: </strong>
                <%= jobfeed_item.work_type %></span>

    <span class="max_budget"><strong>Max Bid: </strong>$
                <%= jobfeed_item.max_budget %></span>

    <span class="overtime"><strong>Pays Overtime: </strong>
                <%= jobfeed_item.overtime ? "Yes" : "No" %>
    </span>

    <span class="start_date"><strong>Start Date:  </strong>
                <%= jobfeed_item.start_date ? 
                jobfeed_item.start_date.strftime("%a, %b. %d, %Y") : "" %>
    </span>

    <span class="duration"><strong>Project Duration: </strong>
                <%= jobfeed_item.duration %> weeks
    </span>

    <span class="work_intensity"><strong>Intensity: </strong>
                <%= jobfeed_item.work_intensity %> hours per week
    </span>

    <span class="skills"><strong>Skills Sought: </strong>
                <%= jobfeed_item.skills %></span>

    <span class="description">
      <strong>Description: </strong><%= jobfeed_item.description %>
    </span>

    <span class="timestamp">Posted
          <%= time_ago_in_words(jobfeed_item.created_at) %> ago.
    </span>

	<% if current_user?(jobfeed_item.user) %>

	    <%= link_to "Delete Post", jobfeed_item, :method => :delete,
	                                     :confirm => "You sure?",
	                                     :title => jobfeed_item.title %>

  </td>

  
  <td class="gravatar">
    <%= link_to gravatar_for(jobfeed_item.user), jobfeed_item.user %>
   </td>
  <% end %>
</tr>

app/views/shared/_jobpost_details.html.erb
<table class="jobposts" summary="User jobposts">
     <tr>
        <td class="jobpost">          
          <span class="location"><strong>Location: </strong>
                                  <%= @job.location %></span>

          <span class="poster"><strong>Posted by: </strong>
                             <%= link_to @job.user.name,
                                           @job.user %>
          </span>

          <span class="work_type"><strong>Work Type: </strong>
                      <%= @job.work_type %></span>

          <span class="max_budget"><strong>Max Bid: </strong>$
                      <%= @job.max_budget %></span>

          <span class="overtime"><strong>Pays Overtime: </strong>
                      <%= @job.overtime ? "Yes" : "No" %>
          </span>
        </td>
        <td class="jobpost">
          <span class="start_date"><strong>Start Date:  </strong>
                      <%= @job.start_date ?
                      @job.start_date.strftime("%a, %b. %d, %Y") : "" %>
          </span>

          <span class="duration"><strong>Project Duration: </strong>
                      <%= @job.duration %> weeks
          </span>

          <span class="work_intensity"><strong>Intensity: </strong>
                      <%= @job.work_intensity %> hours per week
          </span>

          <span class="skills"><strong>Skills Sought: </strong>
                      <%= @job.skills %></span>

			<% if @job.created_at %>
          <span class="timestamp">Posted
                <%= time_ago_in_words(@job.created_at) %> ago.
          </span>
		  <% end %>
        </td>
      </tr>
</table>

<table class="jobposts" summary="User jobposts">
  <tr>
        <td class="jobpost">
          <span class="description">
            <strong>Description: </strong><%= @job.description %>
          </span>
        </td>
</table>

app/views/shared/_jobpost_form.html.erb
<%= form_for @jobpost, :url => { :action => "preview" } do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title %>: <br /><%= f.text_field :title %> <br />
    <%= f.label :location %>: <br /> <%= f.text_field :location %> <br />
    <%= f.label :email, "Reply-To Email" %>: <br /> <%= f.text_field :email %> <br />
    <%= f.label :poster %>: <br /> <%= @jobpost.poster = current_user.name %>
    			     <%= f.hidden_field :poster %> <br />
    <%= f.label :work_type %>: <br /> <%= f.text_field :work_type %> <br />
    <%= f.label :max_budget %>: <br /> <%= f.text_field :max_budget %> <br />

    <%=  f.check_box :overtime %> Overtime <br/>
  
    <%= f.label :start_date, "Start Date" %>:  <br /><%= f.text_field :start_date %> <br />
    <%= f.label :duration, "Duration (number of weeks)" %>:  <br /><%= f.text_field :duration %> <br />
    <%= f.label :work_intensity, "Intensity (hours per week)" %>:  <br /><%= f.text_field :work_intensity %> <br />
    <%= f.label :skills %>:  <br /><%= f.text_field :skills %> <br />
    <%= f.label :description %>: <br /><%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %> 
  <%= render 'shared/error_messages', :object => f.object %>
	<div class="field"> 
		<%= f.text_area :content %>
	</div>
	
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>

<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_usersearch.html.erb
    <% form_for :search, @user_search, :html => {:method => :get} do |f| %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>

        <%= f.label :name_contains, "Name" %><br />
        <%= f.text_field :name_contains %> <br />

        <%= f.label :location_contains, "Location" %><br />
        <%= f.text_field :location_contains %><br />

        <strong>Rating</strong><br/>
        <%= f.label :rating_gte, "Min" %>
        <%= f.text_field :rating_gte, :size => 3 %>
        <%= f.label :rating_lte, "Max" %>
        <%= f.text_field :rating_lte, :size => 3 %><br />

        <strong>No. Jobs Completed</strong><br/>
        <%= f.label :jobs_completed_gte, "From" %>
        <%= f.text_field :jobs_completed_gte, :size => 3 %>
        <%= f.label :jobs_completed_lte, "to" %>
        <%= f.text_field :jobs_completed_lte, :size => 3 %><br />

        <%= f.label :skills_contains, "Skills" %><br />
        <%= f.text_field :skills_contains %><br />

        <%= f.label :resume_contains, "Resume" %><br />
        <%= f.text_field :resume_contains %><br />
        
        <%= f.label :name_or_location_or_skills_or_tagline_or_resume_contains, "Any Keyword" %><br />
        <%= f.text_field :name_or_location_or_skills_or_tagline_or_resume_contains %><br />

        <%#*<strong><u>Availability</u></strong><br/>%>
        <%#= radio_button_tag(:search, :status_gt, 0) %>
        <%#= label_tag(:status_gt, "Available") %><br/>
        <%#= radio_button_tag(:search, :status_lt, 1) %>
        <%#= label_tag(:status_lt, "Unavailable") %><br/>
        <%#= radio_button_tag(:search, :status_gte, 0) %>
        <%#= label_tag(:status_gte, "Both") %><br/>
        <%#*<br/>%>

        <strong>Availability</strong><br/>
        <%= f.label :status_gte, "Min" %>
        <%= f.text_field :status_gte, :size => 3 %>
        <%= f.label :status_lte, "Max" %>
        <%= f.text_field :status_lte, :size => 3 %><br />

      <p class="button"><%= f.submit "Search" %></p>
  <% end %>