config/routes.rb
SampleApp::Application.routes.draw do
 
  resources :users do
    member do
      get :following, :followers, :billable_jobs
    end
  end
 
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]

          resources :jobposts do
            member do
              get :winners
            end
              resources :bids #, :only => [:create, :destroy]
          end

          resources :bids do #, :only => [:create, :destroy] do
              resources :microposts, :only => [:create, :destroy]
          end

  resources :relationships, :only => [:create, :destroy]
  resources :winationships, :only => [:create, :destroy]
  
  root :to => "pages#home"  

  match '/allbids',  :to => 'bids#index'

  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/help',      :to => 'pages#help'
  match '/projects',  :to => 'jobposts#index'
  match '/post_project',  :to => 'jobposts#new'
  match '/preview_project',  :to => 'jobposts#preview'
  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  

end

app/views/layouts/_footer.html.erb
<!--footer starts-->
<div id="footer">
  <div class="footer_inner_row">
    <ul>
      <li class="first"><img src="images/get_in_touch.gif" alt="" /></li>
      <li> <img src="images/phone.gif" alt="" /> 1-800-555-5555</li>
      <li> <img src="images/email.gif" alt="" /> you@yoursite.com</li>
      <li><img src="images/pancile.gif" alt="" />contact Form</li>
      <li> <img src="images/skype.gif" alt="" />YourSkypeUserID</li>
      <li class="last"> <img src="images/link.gif" alt="" /> <a href="#"><img src="images/rss.gif" alt="" /></a> <a href="#"><img src="images/twetter.gif" alt="" /></a> <a href="#"><img src="images/facebook.gif" alt="" /></a> <a href="#"><img src="images/space.gif" alt="" /></a> <a href="#"><img src="images/fliker.gif" alt="" /></a> <a href="#"><img src="images/linkin.gif" alt="" /></a> </li>
    </ul>
    <p>Copyright 2011 <span>Premium Legal Exchange.</span> All Rights  Reserved</p>
    <ul>
        <%= debug(params) if Rails.env.development? %>
    </ul>
  </div>
</div>
<!--footer ends-->

app/views/layouts/_header.html.erb
  <!--header starts-->
  <div id="header">
    <!--top link starts-->
    <div class="top_link">
      <div class="login_area"> <span class="left"></span>
        <ul>
<% if signed_in? %>
          <li class="active">
            <%= link_to "PROFILE", user_path(current_user) %>
          </li>
          <li class="last">
            <%= link_to "LOG OUT", signout_path %>
          </li>
<% else %>
          <li class="active">
            <%= link_to "REGISTER", signup_path %>
          </li>
          <li class="last">
            <%= link_to "LOG IN", signin_path %>
          </li>
<% end %>
        </ul>
        <span class="right"></span> </div>
    </div>
    <!--top link ends-->
    <div class="bottom_row">
      <div class="logo"><img src="images/logo.png" alt="" /></div>
      <!--menu starts-->
      <div id="menu">
        <ul>
          <li class="active"><a href="<%= root_path %>" ><span>Home</span></a></li>
          <li><a href="<%= projects_path %>" ><span> Find Project</span></a></li>
          <li><a href="<%= new_jobpost_path %>"><span>Post Project</span></a></li>
          <li><a href="<%= about_path %>"><span>About us</span></a></li>
          <li class="last"><a href="<%= contact_path %>"><span>Contact</span></a></li>
        </ul>
      </div>
      <!--menu ends-->
    </div>
  </div>
  <!--header ends-->

app/views/layouts/_stylesheets.html.erb
<!--[if less than IE 9]	>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if less than IE 8]	> <%= stylesheet_link_tag 'blueprint/ie' %>	<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  	<title> <%= title %> </title>
	<%= csrf_meta_tag %>
        <%#*<style type="text/css" media="all">%>
          <%#*@import url("public/stylesheets/style.css");%>
        <%#*</style>%>
<!--[if IE 6]>
<script  type="text/javascript" src="public/javascripts/png.js"></script>
<link href="public/stylesheets/ie6.css" rel="stylesheet" type="text/css" />
<![endif]-->

	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag :defaults %>
        <%= init_tinymce_hammer_if_required %>
  </head>
  
    <% if (params[:controller] == 'pages' && params[:action] == 'home') %>
  <body id="home">
    <% else %>
  <body>
    <% end %>

       <div id="wrapper">
                <%= render 'layouts/header' %>
         
                <%= render 'shared/flash_errors' %>
        
          <div id="yield">
            <section class="round">
			<%= yield %>
              </section>
          </div>

      <!--wrapper ends-->
      </div>
		<%= render 'layouts/footer' %>
  </body>
</html>